name: app_chess
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.7
  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.3.5
  google_fonts: ^6.2.1 
  get_it: ^8.0.3
  freezed_annotation: ^2.2.0
  flutter_svg: ^2.0.17
  dio: ^5.7.0
  intl: ^0.19.0
  pusher_channels_flutter: ^2.5.0
  device_info_plus: ^11.2.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  background_color: "#000000"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/images/figures/black/
    - assets/images/figures/white/
    - assets/lang/